### ISSUE TITLE
在mac chrome上打开会卡一下,有时只显示一个很小很小说的窗口,

### ISSUE THREAD

**Issue by xuzhuoyu** [foray1010/Popup-my-Bookmarks#121]
在mac chrome上打开会卡一下,有时只显示一个很小很小说的窗口,根本看不到书签,而且打开很慢,希望有优化下.

**Comment by foray1010** [comment]
I also notice this issue, it appears to be an unfixed bug only on macOS chrome
https://bugs.chromium.org/p/chromium/issues/detail?id=428044

will try to have a look at the hacky workaround

**Comment by foray1010** [comment]
I didn't see this problem on v6, if you still facing the same problem, please reopen this issue
