### ISSUE TITLE
missing from chrome app store

### ISSUE THREAD

**Issue by michealo** [foray1010/Popup-my-Bookmarks#122]
noticed i could not install my favorite bookmark manager any longer, what happened?

**Comment by foray1010** [comment]
thanks for reminding! because of chrome extension store new policy, I have to add privacy policy in order to list on chrome extension store again
I have already added (https://github.com/foray1010/Popup-my-Bookmarks/blob/master/PRIVACY.md), guess it will be listed a few days after.

**Comment by foray1010** [comment]
published
