### ISSUE TITLE
Display issue under windows 10

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [foray1010/Popup-my-Bookmarks#123]
when open the menu, chrome start to flash black across the screen. happens both when open general menu and sub-folder menu. when a menu is opened, it no more flashes.

**Comment by foray1010** [comment]
as I do not have a windows 10 device, does this issue still exist? can anyone confirm?

**Comment by silou** [comment]
Yes, I got it , unable to acces only the 1st tab of config (Named Général) , others tabs work well.

**Comment by foray1010** [comment]
@silou seems yours is about options page? if you cannot access General page, how can you access to other tabs?

**Comment by silou** [comment]
Hi,

Thanks for answering so fast: I made you a  little GIF to see that in action. It moves faster than the GIF in real life. 1st <Config Tab> not and all other things seems OK, I think : https://drive.google.com/open?id=1c5bjWNCfILaiOeIX20hwDhxU3c6dNCj1

**Comment by foray1010** [comment]
@silou seems the problem is the description in french is too long. I cannot reproduce in macos but I have published `5.3.2` which extended the options page width, see if it fixes your problem

**Comment by silou** [comment]
@foray1010 ,

Thanks, it seems to be working fine for me.
Have a good day.

**Comment by foray1010** [comment]
nice, I am closing this issue since no further info from original reporter
