### ISSUE TITLE
How to open a popup window with a shortcut key?

### ISSUE THREAD

**Issue by hxse** [foray1010/Popup-my-Bookmarks#1415]
And automatically focuses the cursor on the search bar.

**Comment by foray1010** [comment]
It can be done now by using `Alt+Shift+B`
It won't focus the cursor on the search bar , but if you press any key, it will automatically focus on the search bar

**Comment by Leh2** [comment]
@foray1010 has the shortcut changed? Can't get `Alt+Shift+B` to work on windows.

**Comment by foray1010** [comment]
@Leh2 I didn't change the shortcut, can you try reset the shortcut in `chrome://extensions/shortcuts`?
