### ISSUE TITLE
Bookmark Manager won't load

### ISSUE THREAD

**Issue by svescapade** [foray1010/Popup-my-Bookmarks#144]
I've been using Popup My Bookmarks for several days on a new computer.  Today when I started up I got this message:
eemcgdkfndhakfknompkggombfjjjeno is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

I disabled all my extensions, rebooted, and tried everything I could think of.  The PmB icon is still there but the dropdown menu is missing the "Bookmarks" option which I see on my old PC.  It still shows "Imported bookmarks" and "Other Bookmarks".  Any ideas?

**Comment by foray1010** [comment]
I think it is chrome's error, the dropdown menu is managed by chrome itself and also `eemcgdkfndhakfknompkggombfjjjeno` is not PmB's extension id but `mppflflkbbafeopeoeigkbbdjdbeifni`
