### ISSUE TITLE
Update search results after each keystroke without lag

### ISSUE THREAD

**Issue by alon91** [foray1010/Popup-my-Bookmarks#159]
The extension is _so_ much faster with the launch of [v5.2](https://github.com/foray1010/Popup-my-Bookmarks/issues/7) -- really wonderful! There is now only one tweak I'd love to see: search results updating after each keystroke rather than after typing is paused.

- Current behavior: search results do not update until about .5 seconds after a keystroke. This small lag slows down workflows (and I use the extension dozens of times each day!)
- Desired behavior: update search results instantly on keystroke. This is how the Chrome address bar works, as well as similar extension [Bookmark Express](https://chrome.google.com/webstore/detail/bookmark-express/edgcdcdceojjbiebdbgmacecicaknjih).

**Comment by foray1010** [comment]
I added 300ms debounce delay because I was thinking it will make the overall performance better because search function doesn't need to be fired EVERY TIME user type a character

I can remove it in next version to see how things work out

**Comment by alon91** [comment]
It would be so cool to experiment with  a version of the extension that has 0ms delay. It is so satisfying to see results update in real time in things like the Chrome search bar, and the same experience in PMB would be great, especially if it doesn't affect performance, etc.

Thank you as always!

**Comment by foray1010** [comment]
removed the delay on https://github.com/foray1010/Popup-my-Bookmarks/commit/850c9ec5fb4200a5d6892a2332d6403f8612c749
will be released in next version

**Comment by alon91** [comment]
Yes!! So excited to experiment with a version that has no delay 👏👏👏

Thank you so much for all the hard work here!!

**Comment by foray1010** [comment]
5.3.0 is published :)

**Comment by alon91** [comment]
Just testing now and WOW -- I am **loving** how search results update in real time! Seems like a small tweak but it will make a huge difference in my workflows. Thank you so much, Alex. This extension rocks!!
