### ISSUE TITLE
wrong bookmark opening occasionally (v5.3 / 5.3.1)

### ISSUE THREAD

**Issue by alon91** [foray1010/Popup-my-Bookmarks#164]
Hello!

Since upgrading to v5.3 and 5.3.1 I see a new strange behavior that is hard to reproduce: I select one bookmark but a different one opens up. This is not easily reproduced, if it happens once it will continue to happen in the same tab for a while but opening a new tab usually resolves the issue. This happens once every 20-30 searches.

One example that I just tried:

* Opened PMB with keyboard shortcut, searched for 'gamma'
* The bookmark with title 'gamma bug' shows up in PMB. It is the only bookmark that appears.
* I select the bookmark by hitting `Enter`
* An unrelated bookmark with title 'dcm login log in (ANALYTICS #1)' with [this](https://ddm.google.com/analytics/dfa/#insights/dashboard) opens instead

Trying the same search in the same tab for the next few minutes has the same behavior. Executing the search in a new tab resolves this issue.

Happy to share more details if helpful. Let me know if there's logging or other info you can use. Thank you as always!

**Comment by foray1010** [comment]
@alon91 as v6 is rewritten from the bottom, I am not sure if this bug still exists, could u try to reproduce it again?

**Comment by alon91** [comment]
So far I have gotten zero wrong bookmarks opening up. Extensions working perfectly -- thank you!!

Closing this bug. I will re-open if this happens again 💪
