### ISSUE TITLE
[Feature Request] Show which bookmark is open

### ISSUE THREAD

**Issue by lonix1** [foray1010/Popup-my-Bookmarks#1706]
It would be nice to show an indicator (e.g. a fat dot) next to a bookmark, to show that the window is open on that bookmark's URL.

**Comment by foray1010** [comment]
If the url slightly changed, for example from https://www.google.com/search?q=test&start=10 to https://www.google.com/search?q=test&start=20, it won't work. So I wonder how useful this feature is to all users, can u share your use case?

**Comment by lonix1** [comment]
That's a good point, didn't think of it. Especially on single-page websites which route on querystring only.

I was thinking that I have many bookmarked youtube videos, and when looking through them wanted to know which is playing now in the current window, so I don't click that bookmark again.

Feel free to close if you think it's not possible. Thanks for a great extension, I enjoy using it!
