### ISSUE TITLE
Feature Request: Popup Folder Contents Window Automatically When Hovering on Folder Name

### ISSUE THREAD

**Issue by ckb-reh** [foray1010/Popup-my-Bookmarks#2013]
Title says it all. Many (most ?) other bookmark extensions work this way & it's very, very convenient. Otherwise perfect. Thanks.

**Comment by foray1010** [comment]
What do u mean? Can u share some screenshots from other extension?

**Comment by ckb-reh** [comment]
Absolutely- thanks for asking!

The screenshots are of the chrome extension "Bookmarks Menu." Capture 001 is after clicking one time on the extension's yellow star icon. Cursor is still on it. Capture 002 is after sliding the cursor down over the "Weather" folder name. The left window always pops up automatically & immediately shows the contents of whichever folder the cursor is over without any need to click again.

I mentioned "hovering" in my title which implies pausing on top of a folder name. Actually, "Bookmarks Menu" pops up each folder's contents immediately as the mouse slides over the folder names, no pause or hover is needed. That's nice.

I like both extensions, but this one has more tools.  I especially like the bookmark adding & editing features, they're very convenient.

Thanks. Looks like the screenshots got added in the reverse order & 002 is shown first.

![capture_002_bookmarks menu extension](https://user-images.githubusercontent.com/59519544/164994491-04f49451-190d-4161-bbc2-2ac411a8f269.jpg)
![capture_001_bookmarks menu extension](https://user-images.githubusercontent.com/59519544/164994493-e0f77167-5f27-4054-9552-821376f41057.jpg)

**Comment by foray1010** [comment]
Hover on a folder -> show all bookmarks of the folder on other side right?
That is the default behavior of this extension, did you turn on the setting `Open folders by Left Click`? It will disable this behavior.

**Comment by ckb-reh** [comment]
You're a genius, I'm a dunce, thank you! I didn't pick up/figure out what that setting did & must've set it somewhere along the line while checking out the extension. Sorry. I truly appreciate that you took the time & made the effort to ask me for more info & then tell me what I was doing wrong. You must've been shaking your head. :) The extension is great & I'll be using it from now on.

**Comment by foray1010** [comment]
np, enjoy the extension!
