### ISSUE TITLE
Option to search function and order by open times

### ISSUE THREAD

**Issue by hilen** [foray1010/Popup-my-Bookmarks#2180]
Hi, thanks for the extension, it's so fast and useful. And could you please add an option : order by search and open times.

**Comment by foray1010** [comment]
Unfortunately Chrome extension api does not provide open times to us: https://developer.chrome.com/docs/extensions/reference/bookmarks/#type-BookmarkTreeNode

**Comment by hilen** [comment]
okay, I found this extension's last update time is 2020.11, but the repo of github is updating. How can I get the lastest version  on the chrome store?

**Comment by foray1010** [comment]
There are a couple of huge refactorings since the latest version, but I haven't tested if all the features work fine. If you are interested, welcome to clone & build and let me know!
