### ISSUE TITLE
Cannot open bookmarks pointing to local files

### ISSUE THREAD

**Issue by alon-to** [foray1010/Popup-my-Bookmarks#2544]
Setup details --
* Operating system: Chrome OS
* Chrome version: 121.0.6167.188 (official)
* Popup My Bookmarks version: 8.0.0

Steps to recreate --
* Save bookmark pointing to a local file (example: `file:///home/chronos/u-623ffb263ac82eac6caf/MyFiles/test.txt`)
* Attempt to open local file via bookmark using PMB

Observations --
* Expected behavior: PMB opens the local file
* Observed behavior: selecting the bookmark in the menu has no effect -- PMB remains open with the bookmark highlighted, with nothing changing

Notes --
* It is possible to open file from a file management app
* PMB successfully opened Chrome OS local files via bookmarks until sometime in last six months. Perhaps a change in Chrome OS permissions?

Other notes --
* PMB has been an invaluable tool in my daily flow since 2018. Thank you so much for building and maintaining such a useful tool!

**Comment by foray1010** [comment]
@alon-to There is an option `Allow access to file URLs` you need to turn it on manually in the extension details pages. But thanks for reporting, I should probably add some guidelines in the extension.

Closing this issue, lemme know if it does not work.
