### ISSUE TITLE
Cant get "Support all kind of separators in separatethis.com" to work in 5.0.

### ISSUE THREAD

**Issue by Andy2244** [foray1010/Popup-my-Bookmarks#33]
Hi,

how is this feature supposed to work? I changed the url in the code to "http://separatethis.com/solid.html", but still get the old "-------" version? I also can't find a setting/drop-down list anywhere, to change the separator style?

thx
Andy

**Comment by foray1010** [comment]
This feature actually means we can recognize all kind of bookmark where url starts with `http://separatethis.com/` as a separator in the system
Recognize it as separator bring us two features
1. the bookmark will become grey in color and with lower height
2. when you click `menu` -> `sort by name`, we will only sort within separator


`-------` is actually the bookmark title, we do not have any handling on this

**Comment by Andy2244** [comment]
ah oki thx
