### ISSUE TITLE
First typed character not captured by PMB (v6.0)

### ISSUE THREAD

**Issue by alon91** [foray1010/Popup-my-Bookmarks#465]
This is happening across multiple browsers on Chrome (Version 73.0.3683.114) and Windows. Seems to have been introduced with v6.0.

Steps to reproduce:

1. Trigger the PMB extension (via keyboard shortcut or mouse)
2. Observe that the typing cursor is not active in the search box
3. Attempt to enter one character. Observe that the character is not entered in the search box, and that instead the cursor suddenly appears in the search box.
4. Attempt to enter one character. Observe that the character appears in the search box as expected.

So effectively the first character entered is always lost. Thanks as always for PMB -- as mentioned before it's a hugely useful extension for me.

**Comment by foray1010** [comment]
It is intended to not focus on search box at first because non-english input method in windows may appear a small box and cover some of the bookmarks, which is quite annoying. But it should focus and type in search box when enter one character, it is a bug, I will fix it

**Comment by alon91** [comment]
Thank you as always! I'll also take this opportunity to humbly mention that I'd love your thoughts on https://github.com/foray1010/Popup-my-Bookmarks/issues/160. It's the one thing that really breaks my flow when using PMB! :)

**Comment by foray1010** [comment]
6.0.1 is released to fix this bug (may have to wait for 1hr to broadcast the release) 🎉 if it doesn't work, plz reopen this issue

**Comment by alon91** [comment]
Success! Thanks so much for fixing this so quickly. PMB is the best!
