### ISSUE TITLE
Request: left click OR enter

### ISSUE THREAD

**Issue by alon91** [foray1010/Popup-my-Bookmarks#538]
The 'Control' section in PmB options has the ability to trigger alternate actions by doing left click + `CTRL` or `Shift`.

But when using the keyboard only and doing `CTRL` + `Enter` or `Shift` + `Enter`, the regular ("Left Click to open bookmarks in") action happens.

Is it possible to have `CTRL` / `Shift` + `Enter` trigger the same things as `CTRL` / `Shift` + left click?

![image](https://user-images.githubusercontent.com/35006176/59958608-537c4300-945e-11e9-82e9-f14b9500011d.png)

Thank you as always -- I love PmB!!

**Comment by foray1010** [comment]
Nice! It is possible and should be a quick fix, I will see if I can make it tmr

**Comment by alon91** [comment]
Thank you @foray1010! Looking forward to this enhancement :)

**Comment by foray1010** [comment]
@alon91 shipped in 6.2.0💪 (may take up to 60 minutes to appear in the Chrome Web Store)

**Comment by alon91** [comment]
Works great -- thank you as always!
