### ISSUE TITLE
No longer works after 5.0.1 update

### ISSUE THREAD

**Issue by chrisvio** [foray1010/Popup-my-Bookmarks#61]
Only a tiny box opens. See screenshot below. I'm using MacOS 10.12.3 on a 15.4-inch (2880 x 1800) display and Chrome version 57.0.2987.110 (64-bit).

<img width="1029" alt="tinybox" src="https://cloud.githubusercontent.com/assets/16415311/24332153/852cf8be-120f-11e7-8b46-69485adab487.png">

**Comment by foray1010** [comment]
hmm... I thought it only happen in old version. My observation is, if you have a long enough bookmark list, it doesn't happen (in old version, it is opposite)
honestly I don't know why, it only happen on macOS, it will be fine if you retry multiple time
I will try to fix it

**Comment by foray1010** [comment]
related bug: https://bugs.chromium.org/p/chromium/issues/detail?id=428044

**Comment by AbsurdMagpieScrutinies** [comment]
On Debian Linux, 18 months later, still the same error. This extension now does not work at all. 

After clearing errors, trying to run, this error is reported:

![popup my bookmarks error](https://user-images.githubusercontent.com/8019455/47613105-65832d00-daed-11e8-8d34-1ece24ebb872.jpg)


-------------------------------------------
Linux 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux

prompt> opera-beta --version                                            
57.0.3098.6 

Browser identification
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.9 Safari/537.36 OPR/57.0.3098.6 (Edition beta)

**Comment by foray1010** [comment]
@chrisvio @AndreasLengkeek can you try again on v6? if this issue still exist, I will reopen this issue

@AbsurdMagpieScrutinies I don't have resource to support Opera, but I hope v6 fix your problem. If it doesn't, I suggest you could take a look at source code and try to fix it :)
