### ISSUE TITLE
New Ctrl+B functionality causes issues when using text editors

### ISSUE THREAD

**Issue by kaitan32** [foray1010/Popup-my-Bookmarks#63]
My job requires the use of a text editor to do a lot of formatting, especially things like bold/italics/underline. The new Ctrl+B option to open PmB means I can no longer use bold formatting via the keyboard shortcut, which is a huge pain. Is it possible to make this shortcut customizable? I won't be able to use the extension otherwise.

**Comment by foray1010** [comment]
It can be customised, but it is better for me to change the default shortcut to something else
I will release a new version today to fix it

**Comment by kaitan32** [comment]
Great, how would I customize the shortcut in the meantime? I didn't see anything in the options.

**Comment by foray1010** [comment]
You can change it at the bottom of chrome://extensions/ => `Keyboard shortcuts`
I will change it to `Ctrl / Command(macOS) + Shift + B`

**Comment by kaitan32** [comment]
Works perfectly, thanks. Enjoy a drink on me :)

**Comment by foray1010** [comment]
`5.0.2` is released (https://github.com/foray1010/Popup-my-Bookmarks/releases/tag/5.0.2)
will take less than one hour for chrome extension store to process and push the update to all users
Thanks for the report @kaitan32 !

**Comment by n8wood** [comment]
@foray1010 , unfortunately the new shortcut interferes with one used by Chrome to show/hide the Bookmarks Toolbar.

**Comment by foray1010** [comment]
true... I will change it again
meanwhile please change it at the bottom of chrome://extensions/ => Keyboard shortcut

**Comment by foray1010** [comment]
Changed to `Alt + Shift + B`
