### ISSUE TITLE
Ctrl+B interfering with rich text editors

### ISSUE THREAD

**Issue by n8wood** [foray1010/Popup-my-Bookmarks#70]
Hi, this is a very useful extension, but I'm wondering if there is any way to change the shortcut for opening the menu. Ctrl+B is often used to make text bold in rich text editors and I use that often.

**Comment by foray1010** [comment]
Related issue: https://github.com/foray1010/Popup-my-Bookmarks/issues/63
I changed to `Ctrl / Command(macOS) + Shift + B`, can u reinstall and try again?
