### ISSUE TITLE
Options not opening

### ISSUE THREAD

**Issue by Soninmyeyes** [foray1010/Popup-my-Bookmarks#787]
Although Options is in the extension's context menu, it does not open reliably. Usually, it just opens the Chrome Manage Extension page. When the Options popup does open, it operates sluggishly, and dropdown menus either don't open at all or open as an unselectable black box.

This issue was first reported in the Support section of the extension's Chrome Store page on May 26, 2019.

**Comment by foray1010** [comment]
I can reproduce options page cannot be opened, but the dropdown menu works fine.

Could u provide your
1. OS version
2. Chrome version

**Comment by foray1010** [comment]
@Soninmyeyes version `7.0.1` should fix the options page, can u try? (should be available within a few hours)

**Comment by foray1010** [comment]
closing due to inactive
