### ISSUE TITLE
Control-B opens window

### ISSUE THREAD

**Issue by fidian** [foray1010/Popup-my-Bookmarks#94]
I'm on Linux and I use Google Docs a lot. This extension overrides my use of Control-B to make text bold. I don't see a checkbox or setting in the options to disable this hotkey or map it to something else. Would you consider adding either a way to disable the hotkey or a way to configure it?

**Comment by foray1010** [comment]
Related issue: https://github.com/foray1010/Popup-my-Bookmarks/issues/63
I changed to `Alt + Shift + B`, please reinstall

**Comment by fidian** [comment]
Did you publish the new version? When I view the app, I still see the same version number as what I have installed, version 5.1.1.

![image](https://user-images.githubusercontent.com/428348/27542381-b5aceea6-5a4c-11e7-8782-cb521795d054.png)

https://chrome.google.com/webstore/detail/popup-my-bookmarks/mppflflkbbafeopeoeigkbbdjdbeifni?hl=en

**Comment by foray1010** [comment]
nope, it is just because Chrome doesn't allow me to change the hotkey once it is set. the only way to change it is to reinstall the extension
Or, You can change it at the bottom of chrome://extensions/ => Keyboard shortcuts

**Comment by fidian** [comment]
Awesome, thanks for explaining why I need to uninstall and reinstall, plus thanks for pointing out where the keyboard bindings are! A+
